[package]
name = "sabita_tui"
description = "A TUI for the Sabita sudoku package"
version = "0.1.0"
authors = ["Mike AUBENAS"]
edition = "2021"
readme = "README.md"
rust-version = "1.83.0"
repository = "https://github.com/MikyStar/Sabita-TUI"
license = "MIT"

[dev-dependencies]
rusty-hook = "^0.11.2"
