[package]
name = "sabita_tui"
description = "A TUI for the Sabita sudoku package"
version = "0.2.0"
authors = ["Mike AUBENAS"]
edition = "2021"
readme = "README.md"
rust-version = "1.83.0"
repository = "https://github.com/MikyStar/Sabita-TUI"
license = "MIT"

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]
crossterm = "0.29.0"
humanize-duration = "0.0.7"
ratatui = "0.29.0"
regex = "1.12.2"
sabita = "0.5.3"
